"use strict";
/* ============================================================
   QUESTION BANK
   ============================================================ */
const QUESTIONS = {
  mage:[ // Front-End
    {q:"Which CSS property sets space INSIDE an element, between content and its border?",
     a:["margin","padding","gap","border-spacing"],c:1},
    {q:"In JavaScript, what extra check does `===` do that `==` does not?",
     a:["Nothing, they're identical","Compares type with no coercion","Only compares references","Checks truthiness"],c:1},
    {q:"Which React Hook runs side effects after a component renders?",
     a:["useState","useMemo","useEffect","useRef"],c:2},
    {q:"What does the CSS `position: absolute` value do?",
     a:["Keeps it in normal flow","Positions vs nearest positioned ancestor","Fixes it to the viewport","Centers it automatically"],c:1},
    {q:"What is the DOM?",
     a:["A CSS framework","A tree representation of the page","A build tool","A database engine"],c:1},
    {q:"What does `event.preventDefault()` do?",
     a:["Stops event bubbling","Prevents the default browser action","Removes the element","Reloads the page"],c:1},
    {q:"In CSS specificity, which wins?",
     a:["Element selector","Class selector","ID selector","They're equal"],c:2},
    {q:"What does `box-sizing: border-box` change?",
     a:["Adds a visible border","Includes padding & border in width","Doubles the margin","Disables overflow"],c:1},
    {q:"What does `flex: 1` mostly control on a flex item?",
     a:["Its z-index","How it grows to fill space","Its font size","Its border radius"],c:1},
    {q:"Which method stops an event from bubbling up the DOM?",
     a:["preventDefault()","stopPropagation()","returnFalse()","cancelBubble()"],c:1},
  ],
  fighter:[ // Back-End
    {q:"Which HTTP method is idempotent and replaces a resource entirely?",
     a:["POST","PATCH","PUT","CONNECT"],c:2},
    {q:"What does HTTP status code 404 mean?",
     a:["Server error","Created","Not Found","Unauthorized"],c:2},
    {q:"What does a database index primarily improve?",
     a:["Write throughput","Query / read lookup speed","Storage size","Backup time"],c:1},
    {q:"In ACID, what does the 'A' stand for?",
     a:["Availability","Atomicity","Authentication","Allocation"],c:1},
    {q:"What is the main purpose of a primary key?",
     a:["Encrypt the row","Uniquely identify each row","Sort the table","Compress data"],c:1},
    {q:"Which status code best signals a resource was created?",
     a:["200 OK","201 Created","204 No Content","302 Found"],c:1},
    {q:"What is database normalization mainly for?",
     a:["Increasing redundancy","Reducing redundancy & anomalies","Encrypting columns","Speeding all writes"],c:1},
    {q:"A load balancer's core job is to…",
     a:["Cache static files","Distribute traffic across servers","Compile code","Store sessions"],c:1},
    {q:"What is a deadlock?",
     a:["A crashed server","Two+ tasks each waiting on the other's lock","A full disk","An expired token"],c:1},
    {q:"HTTP is best described as a … protocol.",
     a:["Stateful","Stateless","Encrypted by default","Peer-to-peer"],c:1},
  ],
  thief:[ // Cyber-Security
    {q:"What is Cross-Site Scripting (XSS)?",
     a:["Stealing CPU cycles","Injecting malicious scripts into pages","A DNS outage","A type of backup"],c:1},
    {q:"What best prevents SQL injection?",
     a:["String concatenation","Parameterized / prepared queries","Hiding the DB port","Using GET requests"],c:1},
    {q:"What does HTTPS add over HTTP?",
     a:["Faster downloads","Encryption in transit","More storage","Better SEO only"],c:1},
    {q:"What is the principle of least privilege?",
     a:["Grant admin to all","Give the minimum access needed","Disable all logging","Share one root account"],c:1},
    {q:"Why add a 'salt' when hashing passwords?",
     a:["To speed up login","To defeat precomputed/rainbow tables","To compress the hash","To encrypt the salt"],c:1},
    {q:"CSRF attacks are best mitigated with…",
     a:["Bigger servers","Anti-CSRF tokens / SameSite cookies","Password hashing","HTTP only"],c:1},
    {q:"Symmetric encryption uses…",
     a:["Two different keys","The same key to encrypt & decrypt","No key at all","Only a hash"],c:1},
    {q:"Phishing is primarily an example of…",
     a:["A buffer overflow","Social engineering","A SQL attack","A race condition"],c:1},
    {q:"What is a 'zero-day' vulnerability?",
     a:["A bug fixed long ago","An unknown flaw exploited before a patch","A daily password reset","A type of firewall"],c:1},
    {q:"What property does hashing provide that encryption doesn't aim for?",
     a:["It is reversible","It is one-way / irreversible","It needs no input","It compresses files"],c:1},
  ]
};
